config/routes.rb
Rails.application.routes.draw do

  resources :doctors, :appoints, :availability

  root 'users#show'

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get "profile" => "users#show"
  get "signup" => "users#new"
  post "signup" => "users#create"
  delete "delete/:id" => "users#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appoint.rb
class Appoint < ApplicationRecord
  belongs_to :doctor
  belongs_to :user

  before_save :availability_default

  def availability_default
    self.complaint ||= "unavailable"
  end

end

app/controllers/appoints_controller.rb
class AppointsController < ApplicationController
  before_action :set_appoint, only: [:show, :edit, :update, :destroy]
  before_action  :is_admin, only: [:index]
  before_action  :is_owner_or_admin, only: [:edit,:update,:destroy]

  # GET /appoints
  # GET /appoints.json
  def index
    @appoints = Appoint.all
  end

  # GET /appoints/1
  # GET /appoints/1.json
  def show
  end

  # GET /appoints/new
  def new
    @appoint = Appoint.new

  end

  # GET /appoints/1/edit
  def edit
  end

  # POST /appoints
  # POST /appoints.json
  def create
    puts ">>>appoint_params: #{appoint_params.inspect}"
    @appoint = Appoint.new(appoint_params)

    respond_to do |format|
      if @appoint.save
        format.html { redirect_to @appoint, notice: 'Appoint was successfully created.' }
        format.json { render :show, status: :created, location: @appoint }
      else
        format.html { render :new }
        format.json { render json: @appoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appoints/1
  # PATCH/PUT /appoints/1.json
  def update
    respond_to do |format|
      if @appoint.update(appoint_params)
        format.html { redirect_to @appoint, notice: 'Appoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @appoint }
      else
        format.html { render :edit }
        format.json { render json: @appoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appoints/1
  # DELETE /appoints/1.json
  def destroy
    @appoint.destroy
    respond_to do |format|
      format.html { redirect_to appoints_url, notice: 'Appoint was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appoint
      @appoint = Appoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appoint_params
      params.require(:appoint).permit(:doctor_id, :user_id, :complaint, :speciality, :date, :time_slot)
    end

end

app/helpers/appoints_helper.rb
module AppointsHelper
end

app/views/appoints/_form.html.erb
<%= form_for(appoint) do |f| %>
  <% if appoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appoint.errors.count, "error") %> prohibited this appoint from being saved:</h2>

      <ul>
      <% appoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :speciality %>
    <%= f.select :speciality, Doctor.all.collect {|x| [x.speciality,x.speciality]}, { include_blank: 'Please select one' } %>
  </div>

  <div class="field">
    <%= f.label :doctor %>
    <%= f.select :doctor_id, Doctor.all.reorder('name ASC').collect {|x| [x.name,x.id,{:class => "toggle_doctors hidden #{x.speciality}"}]}, { include_blank: 'Select Doctor' } %>
  </div>

  <div class="field">
    <%= f.label :complaint %>
    <%= f.text_area :complaint %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.number_field :date, placeholder: 'YYYYMMDD' %>
  </div>

  <div class="field">
    <%= f.label :Time %>
    <%= f.select :time_slot, [8,9,10,11,12,13,14,15,16,17,18,19,20].collect {|x| [x.to_s+":00 - "+(x+1).to_s+":00",x]}, { include_blank: 'Select Time' } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <input type="hidden" name="appoint[user_id]" value="<%=@current_user.id%>">
<% end %>

app/views/appoints/edit.html.erb
<h1>Editing Appoint</h1>

<%= render 'form', appoint: @appoint %>

<%= link_to 'Show', @appoint %> |
<%= link_to 'Back', appoints_path %>

app/views/appoints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appoints</h1>

<table>
  <thead>
    <tr>
      <th>Doctor</th>
      <th>User</th>
      <th>Complaint</th>
      <th>Speciality</th>
      <th>Date</th>
      <th>Time slot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appoints.each do |appoint| %>
      <tr>
        <td><%= appoint.doctor_id %></td>
        <td><%= appoint.user_id %></td>
        <td><%= appoint.complaint %></td>
        <td><%= appoint.speciality %></td>
        <td><%= appoint.date %></td>
        <td><%= appoint.time_slot %></td>
        <td><%= link_to 'Show', appoint %></td>
        <td><%= link_to 'Edit', edit_appoint_path(appoint) %></td>
        <td><%= link_to 'Destroy', appoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appoint', new_appoint_path %>

app/views/appoints/new.html.erb
<h1>Make an Appoint</h1>

<%= render 'form', appoint: @appoint %>

<%= link_to 'Back', profile_path %>

app/views/appoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doctor:</strong>
  <%= @appoint.doctor.name %>
</p>

<p>
  <strong>Complaint:</strong>
  <%= @appoint.complaint %>
</p>

<p>
  <strong>Speciality:</strong>
  <%= @appoint.speciality %>
</p>

<p>
  <strong>Date:</strong>
  <%= @appoint.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @appoint.time_slot %>
</p>

<%= link_to 'Edit', edit_appoint_path(@appoint) %> |
<%= link_to 'Back', profile_path %>