config/routes.rb
Rails.application.routes.draw do

  resources :doctors, :appoints, :availability

  root 'users#show'

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get "profile" => "users#show"
  get "signup" => "users#new"
  post "signup" => "users#create"
  delete "delete/:id" => "users#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appoints

  before_save :type_admin_default


  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false}

  # validates :password,
  validates :password, confirmation: true,
  length: { in: 8..72 },
  on: :create

  validates :password_confirmation, presence: true

  has_secure_password

  def self.authenticate(params)
    User.find_by_email(params[:email]).try(:authenticate, params[:password])
  end


  def type_admin_default
    self.account ||= "patient"
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :is_authenticated, only: [:show,:edit,:destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user_appoints = Appoint.where(user_id: current_user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user= User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to profile_url, notice: 'User account created successfully'
    else
      render :new, notice: 'Invalid details'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_user
    #   @user = User.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for :user do |f| %>
<div class="field">
  <%= f.label :email %>
  <%= f.email_field :email, placeholder: "Enter your email" %>
</div>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "Enter your password" %>
</div>
<div class="field">
  <%= f.label :confirm_password %>
  <%= f.password_field :password_confirmation, placeholder: "Confirm password" %>
</div>
<div class="actions">
  <%= f.submit "Login" %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.type %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', '../' %>

app/views/users/show.html.erb
<strong>Account of <%= @current_user.email %>,</strong>

<p>You have:</p>

<% if @user_appoints.length === 0 %>
<p>
  No appointments made. <a href="/appoints/new">Make an appointment now.</a>
</p>
<% else %>
  <ul>
    <% @user_appoints.each do |appoint| %>
      <li>
        Appointment on <%= appoint.date.to_s[0,4] %>/<%= appoint.date.to_s[4,2] %>/<%= appoint.date.to_s[5,2] %> at <%= appoint.time_slot %>:00-<%= appoint.time_slot+1 %>:00 with <%= appoint.doctor.name %>
        <%= link_to 'View', appoint_path(appoint.id) %>
        <%= link_to 'Change', edit_appoint_path(appoint.id) %>
        <%= link_to 'Cancel', appoint, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if @current_user.account == 'admin' %>
<strong>Admin controls:</strong>
<%= link_to 'New Availability', new_availability_path %> |
<%= link_to 'Master schedule', appoints_path %>
<% end %>

<br><br>
<%= link_to 'New Appointment', new_appoint_path %>
<%= link_to 'Log out', logout_path, method: :delete %>