config/routes.rb
Rails.application.routes.draw do

  resources :doctors, :appoints, :availability

  root 'users#show'

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get "profile" => "users#show"
  get "signup" => "users#new"
  post "signup" => "users#create"
  delete "delete/:id" => "users#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/availability_controller.rb
class AvailabilityController < ApplicationController
  before_action  :is_admin, only: [:new]

  def new
    @appoint = Appoint.new
  end

  def index
  end
end

app/helpers/availability_helper.rb
module AvailabilityHelper
end

app/views/availability/index.html.erb
<h1>Availability#index</h1>
<p>Find me in app/views/availability/index.html.erb</p>

app/views/availability/new.html.erb
<h1>//Doctor's unavailability// admin only</h1>

<%= form_for @appoint, :url => appoints_path, :html => { :method => :post } do |f| %>
<div class="field">
  <%= f.label :speciality %>
  <%= f.select :speciality, Doctor.all.collect {|x| [x.speciality,x.speciality]}, { include_blank: 'Please select one' } %>
</div>

<div class="field">
  <%= f.label :doctor %>
  <%= f.select :doctor_id, Doctor.all.reorder('name ASC').collect {|x| [x.name,x.id,{:class => "toggle_doctors hidden #{x.speciality}"}]}, { include_blank: 'Select Speciality' } %>
</div>

<div class="field">
  <%= f.label :date %>
  <%= f.text_field :date, placeholder: "YYYYMMMDD" %>
</div>

<div class="field">
  <%= f.label :Time %>
  <%= f.select :time_slot, [8,9,10,11,12,13,14,15,16,17,18,19,20].collect {|x| [x.to_s+":00 - "+(x+1).to_s+":00",x]}, { include_blank: 'Select Time' } %>
</div>


<div class="actions">
  <%= f.submit %>
</div>
<% end %>

<input type="hidden" name="appoint[user_id]" value="<%=@current_user.id%>">

<%= link_to 'Back to dashboard', profile_url %>